#!/bin/bash

## Based on:
## https://github.com/adi1090x/widgets

## Collect data
cache_dir="$HOME/.cache/eww/weather"
cache_weather_stat=${cache_dir}/weather-stat
cache_weather_degree=${cache_dir}/weather-degree
cache_weather_hex=${cache_dir}/weather-hex
cache_weather_icon=${cache_dir}/weather-icon
cache_weather_humidity=${cache_dir}/weather-humidity

## Weather data
KEY=$(grep -oP 'WEATHER_API_KEY=\K.[A-Za-z0-9]*' ~/.config/eww/.env)
CITY=$(grep -oP 'WEATHER_CITY=\K.[A-Za-z0-9]*' ~/.config/eww/.env)
UNIT="metric"	# Available options : 'metric' or 'imperial'

## Make cache dir
if [[ ! -d "$cache_dir" ]]; then
	mkdir -p ${cache_dir}
fi

## Get data
get_weather_data() {
	url="api.openweathermap.org/data/2.5/weather?id=$CITY&appid=$KEY&cnt=5&units=$UNIT&lang=en"
	weather=`curl -sf ${url}`
	echo ${weather}

	if [ ! -z "$weather" ]; then
		weather_temp=`echo "$weather" | jq ".main.temp" | cut -d "." -f 1`
		weather_humidity=`echo "$weather" | jq ".main.humidity" | cut -d "." -f 1`
		weather_icon_code=`echo "$weather" | jq -r ".weather[].icon" | head -1`
		weather_description=`echo "$weather" | jq -r ".weather[].description" | head -1 | sed -e "s/\b\(.\)/\u\1/g"`

		#Big long if statement of doom
		if [ "$weather_icon_code" == "01d"  ]; then
			## Sunny day
			weather_icon=""
			weather_hex="#ffd86b"
		elif [ "$weather_icon_code" == "01n"  ]; then
			## Sunny night
			weather_icon=""
			weather_hex="#fcdcf6"
		elif [ "$weather_icon_code" == "02d"  ]; then
			## Cloudy day
			weather_icon=""
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "02n"  ]; then
			## Cloudy night
			weather_icon=""
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "03d"  ]; then
			## Cloudy day 2
			weather_icon=""
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "03n"  ]; then
			## Cloudy night 2
			weather_icon=""
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "04d"  ]; then
			## Cloudy day 3
			weather_icon=""
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "04n"  ]; then
			## Cloudy night 3
			weather_icon=""
			weather_hex="#adadff"
		elif [ "$weather_icon_code" == "09d"  ]; then
			## Rainy day
			weather_icon=""
			weather_hex="#6b95ff"
		elif [ "$weather_icon_code" == "09n"  ]; then
			## Rainy night
			weather_icon=""
			weather_hex="#6b95ff"
		elif [ "$weather_icon_code" == "10d"  ]; then
			## Rainy day 2
			weather_icon=""
			weather_hex="#6b95ff"
		elif [ "$weather_icon_code" == "10n"  ]; then
			## Rainy night 2
			weather_icon=""
			weather_hex="#6b95ff"
		elif [ "$weather_icon_code" == "11d"  ]; then
			## Storm day
			weather_icon=""
			weather_hex="#ffeb57"
		elif [ "$weather_icon_code" == "11n"  ]; then
			## Storm night
			weather_icon=""
			weather_hex="#ffeb57"
		elif [ "$weather_icon_code" == "13d"  ]; then
			## Snow day
			weather_icon=""
			weather_hex="#e3e6fc"
		elif [ "$weather_icon_code" == "13n"  ]; then
			## Snow night
			weather_icon=""
			weather_hex="#e3e6fc"
		elif [ "$weather_icon_code" == "40d"  ]; then
			## Misty day
			weather_icon=""
			weather_hex="#84afdb"
		elif [ "$weather_icon_code" == "40n"  ]; then
			## Misty night
			weather_icon=""
			weather_hex="#84afdb"
		elif [ "$weather_icon_code" == "50d"  ]; then
			## Misty day 2
			weather_icon=""
			weather_hex="#84afdb"
		elif [ "$weather_icon_code" == "50n"  ]; then
			## Misty night 2
			weather_icon=""
			weather_hex="#84afdb"
		else 
			## Unknown
			weather_icon=""
			weather_hex="#adadff"
		fi
		echo "$weather_icon" >  ${cache_weather_icon}
		echo "$weather_description" > ${cache_weather_stat}
		echo "$weather_temp""°C" > ${cache_weather_degree}
		echo "$weather_hex" > ${cache_weather_hex}
		echo "$weather_humidity""%" > ${cache_weather_humidity}
	else
		echo "Weather Unavailable" > ${cache_weather_stat}
		echo "" > ${cache_weather_icon}
		echo "-" > ${cache_weather_degree}
		echo "#adadff" > ${cache_weather_hex}
	fi
}

## Execute
if [[ "$1" == "--getdata" ]]; then
	get_weather_data
elif [[ "$1" == "--icon" ]]; then
	cat ${cache_weather_icon}
elif [[ "$1" == "--temp" ]]; then
	cat ${cache_weather_degree}
elif [[ "$1" == "--hex" ]]; then
	cat ${cache_weather_hex}
elif [[ "$1" == "--humidity" ]]; then
	cat ${cache_weather_humidity}
elif [[ "$1" == "--stat" ]]; then
	cat ${cache_weather_stat}
fi

